name: toucant
description: "A demotivational app that helps you to stay focused on your goals (or not hehe)."

publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  flutter_displaymode: ^0.6.0
  timezone: ^0.9.4
  logging: ^1.2.0
  device_info_plus: ^10.1.2
  animations: ^2.0.11
  intl: ^0.19.0
  dio: ^5.6.0
  dio_smart_retry: ^6.0.0
  go_router: ^14.2.7
  flutter_confetti: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.4.3
  build_runner:
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
