[package]
name = "server"
version = "0.2.2"
edition = "2021"

[dependencies]
axum = "0.7"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.39", features = ["full"] }
