services:
  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:latest
        RUN apt update && \ 
            apt install cron -y
        RUN echo '0 0 * * * rm -rf /etc/nginx/cache/*' | crontab && \
            echo '#!/bin/bash\n\ncron && /docker-entrypoint.sh "$@"' > entrypoint-wrapper.sh && \
            chmod +x /entrypoint-wrapper.sh
        ENTRYPOINT ["/entrypoint-wrapper.sh"]
        CMD ["nginx", "-g", "daemon off;"]
    command: 
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  server:
    container_name: server
    build:
      context: .
      dockerfile_inline: |
        FROM rust:latest
        WORKDIR app
        COPY ./src ./src
        COPY Cargo.toml Cargo.lock .
        RUN cargo build --release && \
            mv ./target/release/server ./server && \
            rm -rf ./src ./Cargo.toml ./Cargo.lock
    command: /app/server
    stop_signal: SIGKILL
    volumes: 
      - ./data.json:/app/data.json:ro
    restart: unless-stopped
